
spring:
  application:
    name: service-turbine
server:
  port: 8769

turbine:
  aggregator:
    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: eureka-ribbon-client,eureka-feign-client  # 配置Eureka中的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
  instanceUrlSuffix: /hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/